apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-alpine
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 20
          hostPort: 20
        - containerPort: 30020
          hostPort: 30020
        - containerPort: 30021
          hostPort: 30021
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /tmp/livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: http21
      port: 21
    - name: http20
      port: 20
    - name: http30020
      port: 30020
    - name: http30021
      port: 30021
  type: LoadBalancer
