apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma-alpine
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /srcs/livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
